### PR TITLE
Set GITHUB_WORKSPACE

### PR DESCRIPTION
**Pull request by FurqanHabibi**
Partial fix to #43.

### CODE REVIEW

**Comment by hohobilly** [comment]
cc/ @freedomofkeima @akawasaki 
We found the issue and a solution (not actually a solution) to this issue.
The cause is that in `minamijoyo/tfupdate@0.6.6` uses a newer alpine image. This includes a newer version of git (2.36.2) compare to `minamijoyo/tfupdate@0.6.5`'s image which has a git version (2.32.0)
The newer git version includes a patch explained in https://github.com/actions/runner-images/issues/6775#issuecomment-1359785199

We believe this patch has a compatibility issue with GA which is explained in these comments:
1. https://github.com/actions/runner-images/issues/6775#issuecomment-1362289684
2. https://github.com/actions/runner-images/issues/6775#issuecomment-1420586459

One solution is to add `git config --global --add safe.directory "$GITHUB_WORKSPACE"` before https://github.com/HENNGE/tfupdate-action/blob/4441a2e2ae8458c09c0007ab1631271212603c12/entrypoint.sh#L83-L84

Or we can simply downgrade to `0.6.5` and wait for the fix.

**Comment by FurqanHabibi** [comment]
Thanks for finding the root cause @hohobilly 👍 

I believe the solution suggested is better than rolling back `minamijoyo/tfupdate`.
I'll incorporate it to this PR.

**Comment by FurqanHabibi** [comment]
The fix is added and confirmed working.

**Review by sharu1204 — APPROVED** [review]
@FurqanHabibi @hohobilly 
Thank you for your research and fix. Merge it.

**Pull request merged**
